### PR TITLE
Notices: update wording for the VaultPress connection notice

### LINKED ISSUE #23: Notices: Clarify wording for “VaultPress needs your attention!”
“VaultPress needs your attention!” notice wording might be clearer. It suggests to Register VaultPress which will redirect to the ValutPress page when `View plans and pricing` primary button clicked. The page does have a way to register a key, but it does clearly highlighted.

Maybe update the CTA to something like "Register VaultPress or purchase a plan"

Site Stats ‹ Testing Jetpack — WordPress 2019-06-14 11-41-21

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #23

This PR updates the wording of the connection notice that is displayed when VaultPress is installed and active on your site, but not configured.

**Before**

image

**After**

image

**Note**

@dereksmart We currently remove the link when on Jetpack pages, since https://github.com/Automattic/jetpack/pull/6963

It's not ideal with this new wording:

image

Should we now revert the changes we had made in Jetpack?

### CODE REVIEW

**Comment by seear** [comment]
No copy review necessary for this PR—the wording came from Editorial in #23.

**Comment by jeherve** [comment]
@seear Right. How do you think we should approach the issue on Jetpack dashboard pages?

**Comment by seear** [comment]
> Should we now revert the changes we had made in Jetpack?

@jeherve would that mean the VaultPress notices would look exactly the same, but with the link in place? And would there be any other impact?

**Comment by jeherve** [comment]
> would that mean the VaultPress notices would look exactly the same, but with the link in place?

Well that would introduce a duplicate link when in the Jetpack settings, since that would essentially mean reverting this:
https://github.com/Automattic/jetpack/pull/6963

**Comment by seear** [comment]
I have to say I don't have a good grasp of why Jetpack needs to strip the links, but I would say that in the scenario where the link is removed, this message isn't particularly worse than it was before.

**Pull request merged**
